#define FRANCAIS "1"
#define ANGLAIS "2"
#define FRENCH "3"
#define ENGLISH "4"
#define panel_width 450
#define panel_height 200
#define six 1
#define optimum_clusters 2
#define maximum_clusters 3
#define MAX_QUERY_STRING_LEN 8096
static int nConcise=36;
